name: easycontainer_dwl
description: DWL_BUSAN_TERMINER(이지컨테이너)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  cupertino_icons: ^1.0.2
  decorated_icon: ^1.2.1
  http: ^0.13.3
  flutter_secure_storage:
  carousel_slider: ^4.0.0
  auto_size_text: ^3.0.0
  syncfusion_flutter_datagrid:
  get: ^4.3.8
  shared_preferences: ^2.0.7
  permission_handler: ^9.2.0
  auto_size_text_field:
  flutter_launcher_icons: ^0.9.2
  animated_stack: ^0.2.0
  toast: ^0.1.5
  fluttertoast: ^8.0.8
  get_storage: ^2.0.3
  intl: ^0.17.0
  package_info: ^2.0.2
  in_app_update: ^3.0.0
  syncfusion_flutter_datepicker:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/image/appIcon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - resources/image/kuls_logo.png
    - resources/image/title.png
    - resources/image/logo_kuls.png
    - resources/image/bg_login.png
    - resources/icon/check_circle.png
    - resources/icon/container.png
    - resources/icon/emer_light.png
    - resources/icon/repeat_rectangle.png
    - resources/icon/rigth_circle.png
    - resources/image/real_container.png
    - resources/image/blue_container.png
    - resources/image/green_container.png
    - resources/image/orange_container.png
    - resources/image/puple_container.png
    - resources/image/grey_container.png
    - resources/image/citron_container.png
    - resources/image/contrF_FRT.png
    - resources/image/contrT_FRT.png
    - resources/image/help.png

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: resources/font/NotoSansKR-Regular.otf
        - asset: resources/font/NotoSansKR-Bold.otf